Repository treasure-data/trino-client-ruby, pull requests merged in 2023-02, with the labels that each got.

#92 Fix for Ruby 3.2.x
  .github/workflows/ruby.yml
  lib/trino/client/faraday_client.rb
  trino-client.gemspec
Labels: bug, doc

#95 CI: Do not trigger "push" event on pull requests
  .github/workflows/ruby.yml
Labels: chore, doc

#94 Faraday 2.x and 1.x cross support
  .github/workflows/ruby.yml
  Gemfile
  lib/trino/client/faraday_client.rb
  lib/trino/client/query.rb
  trino-client.gemspec
Labels: enhancement, doc

#97 ci: fix typo
  .github/workflows/ruby.yml
Labels: chore

#98 linter: Enable linter on lib
  .standard_todo.yml
  lib/trino/client/query.rb
  lib/trino/client/statement_client.rb
Labels: chore, doc

#101 Upgrade minimum ruby version to 2.7 in trino-client-ruby.gemspec
  trino-client-ruby/trino-client-ruby.gemspec
Labels: chore
